---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-web-ui-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-web-ui-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - create
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-web-ui-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-web-ui-controller
subjects:
  - kind: ServiceAccount
    name: spark-web-ui-controller
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-web-ui-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: spark-web-ui-controller
  template:
    metadata:
      labels:
        k8s-app: spark-web-ui-controller
    spec:
      serviceAccount: spark-web-ui-controller
      containers:
        - name: spark-web-ui-controller
          image: nineep/spark-web-ui-controller:0.1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          args:
            - -hostsuffix
            - '.spark-ui.example.com'
